"""Baseline migration for current models

Revision ID: 322bfc77a955
Revises: 
Create Date: 2025-07-01 11:23:35.163733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '322bfc77a955'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chef', schema=None) as batch_op:
        batch_op.alter_column('clover_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('chef_dish_mapping', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clover_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('item_name', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_chef_dish_mapping_clover_id'), ['clover_id'], unique=False)

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('clover_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('clover_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('chef_dish_mapping', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chef_dish_mapping_clover_id'))
        batch_op.drop_column('item_name')
        batch_op.drop_column('clover_id')

    with op.batch_alter_table('chef', schema=None) as batch_op:
        batch_op.alter_column('clover_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
