"""Make item_id nullable in chef_dish_mapping

Revision ID: e1c2519243dd
Revises: 322bfc77a955
Create Date: 2025-07-01 12:31:28.393818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1c2519243dd'
down_revision = '322bfc77a955'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chef_dish_mapping', schema=None) as batch_op:
        batch_op.alter_column('item_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chef_dish_mapping', schema=None) as batch_op:
        batch_op.alter_column('item_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
